# Generated by Django 2.1.1 on 2018-10-04 18:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Expands',
            new_name='Expenses',
        ),
    ]
